#APP
spring.application.name=JacksonApi
#server.port=????

#BASE DE DATOS
spring.datasource.url = jdbc:postgresql://localhost:5432/jackson
spring.datasource.username = postgres
spring.datasource.password = root1234

#JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view = false